### ISSUE TITLE
cabal file category should be Physics

### ISSUE THREAD

**Issue by claudeha** [diagrams/force-layout#6]
I was looking for mass-spring-damper physical modelling on Hackage, it took me too long to remember that force-layout exists (I hadn't found it with any of my search queries).  Currently force-layout's category is "Graphics", which is misleading (it doesn't graphic anything itself) and not very useful for discoverability.

**Comment by byorgey** [comment]
Good point!  Fixed and released as `force-layout-0.3.0.10`.
